### ISSUE TITLE
[Request] Video-tutorial on how to install Farsi language on the game.

### ISSUE THREAD

**Issue by sarvinpakzad** [Ludeon/RimWorld-Farsi#3]
salam. mishe amozeshesh ro to youtube bezarid ya daghigh tozih bedid ??? man copy past ke mikonam to bazi language "persian" ro nemiare aslan. khaheshan Amozeshesh ro betore daghigh bezarid :(

**Comment by danielHero307** [comment]
Hello . please write in English.
There is a tutorial on how to add the Persian language to the game in the Readme section. I have no intention of adding a video tutorial and am busy, so if I have free time, I may post it.

**Comment by sarvinpakzad** [comment]
> Hello . please write in English. There is a tutorial on how to add the Persian language to the game in the Readme section. I have no intention of adding a video tutorial and am busy, so if I have free time, I may post it.

Yes i know, But in the game, it shows Persian words and sentences in reverse. I do not have access to the server (And I don't know how to use the tool you put in the files. cuz .sh and .rb formats dosn't work in the windows). How can I change and reverse all Farsi words at once? Thank you for answering.

**Comment by danielHero307** [comment]
hi,
If you don't intend to use the project source, you can use the project release and put its files in the game.

https://github.com/Ludeon/RimWorld-Farsi/releases

**Comment by sarvinpakzad** [comment]
ش ر و ع 

When i reverce sentences in the notepad++, Inbaram injori dide mishe to bazi

**Comment by danielHero307** [comment]
> ش ر و ع
> 
> When i reverse sentences in the notepad++, Inbaram injori dide mishe to bazi

you do not need to reverse it, if you want to use the project you can use the release file at this link: https://github.com/Ludeon/RimWorld-Farsi/releases(click assets and download Persian language zip)

if you want to contribute to the translation, you can translate it without any changes, I will do it and publish it in the release.

**Comment by sarvinpakzad** [comment]
> > ش ر و ع
> > When i reverse sentences in the notepad++, Inbaram injori dide mishe to bazi
> 
> you do not need to reverse it, if you want to use the project you can use the release file at this link: https://github.com/Ludeon/RimWorld-Farsi/releases (click assets and download Persian language zip)
> 
> if you want to contribute to the translation, you can translate it without any changes, I will do it and publish it in the release.


Wow. it worked. Many fields are still not translated. I try to translate and complete all the fields. Thanks a lot <3
