### ISSUE TITLE
مشکل در اجرا 

### ISSUE THREAD

**Issue by OoAmIrMoHaMaDoO** [Ludeon/RimWorld-Farsi#9]
من تمام کاری که گفتید رو انجام دادم اما متن بازی فارسی نشد کنار مود علامت تعجب هست و انگار با نسخه من سازگار نیست و من جدیدترین نسخه رو دارم مشکل چیست و اینکه توضیحات نصب کمی مختصر و کوتاه هستند و سخت هست فهمیدن اینکه چگونه باید مود رو نصب کرد

**Comment by DanialPahlavan** [comment]
I will create a YouTube video on this topic. You can copy the content into the data folder and adjust the language settings to Persian.

**Comment by OoAmIrMoHaMaDoO** [comment]
این کار را انجام دادم اما زبان بازی فارسی نشد.منتظر فیلم یوتیوب شما خواهم بود.با تشکر

**Comment by DanialPahlavan** [comment]
hi , Youtube video added to README_fa.md .
